# Base image
FROM node:16-alpine

# Create app directory
# WORKDIR /usr/src/app
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install app dependencies
RUN npm install

COPY . .
# Creates a "dist" folder with the production build

ENV RABBITMQ_URL=amqp://localhost:5672
ENV RABBITMQ_HOST=rabbitmq
ENV RABBITMQ_PORT=5672
ENV CONSUMER_QUEUE=process_complete
ENV RECEIVER_QUEUE=receiver_queue

RUN npm run build

USER node

EXPOSE 3000
# Start the server using the production build
CMD ["npm", "run", "start:dev"]
